---
version: '2'
services:
  cerebro:
    image: yannart/cerebro:latest
    container_name: cht-cerebro
    ports:
      - 9000:9000

  elasticsearch:
    build:
      context: ./elasticsearch
    cap_add:
      - IPC_LOCK
    container_name: cht-elasticsearch
    environment:
      - discovery.zen.minimum_master_nodes=1
    image: cht-elasticsearch:5.1.2
    mem_limit: 4g
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs

  logstash:
    build:
      context: ./logstash
    container_name: cht-logstash
    image: cht-logstash:5.1.2
    ports:
      - 5044:5044

  kibana:
    build:
      context: ./kibana
    container_name: cht-kibana
    image: cht-kibana:5.1.2
    ports:
      - 5601:5601
