---
version: '2'
services:
  elasticsearch:
    build:
      context: ./
    cap_add:
      - IPC_LOCK
    container_name: cht-elasticsearch
    environment:
      - discovery.zen.minimum_master_nodes=1
    image: cht-elasticsearch:5.1.2
    mem_limit: 4g
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
